# 应用服务 WEB 访问端口
server:
  port: 9081
# 应用名称
spring:
  application:
    name: rabbitmq-spring
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/nretail_ability_marketing?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://127.0.0.1:3306/本地?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123

  rabbitmq:
    host: 10.68.244.130
    port: 5672
    username: test
    password: 123456
#    template:
#      mandatory: true
#      retry:
#        enabled: true       #重试
#        max-attempts: 2
#        initial-interval: 1000
#        max-interval: 5000
#        multiplier: 2


  #  cloud:
  #    config:
  #      enabled: false
  #      fail-fast: true
  #    stream:
  #      defaultBinder: rabbit
  #      bindings:
  #        output:
  #          destination: reportOrder-dev
  #          content-type: application/json
  #  output:
  #    ansi:
  #      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://priceUser:123456@10.73.129.235:27017/ability_price
  redis:
    url: redis://10.68.245.239:6379
    timeout: 5s
    lettuce:
      pool:
        max-active: 1000
        max-idle: 20
        min-idle: 0
        max-wait: 5s

